name: Post to Slack

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: 8398a7/action-slack@v3.19.0
        with:
          status: ${{ job.status }}
          fields: message,commit,author,ref,took
          text: ${{ github.event_name == 'workflow_dispatch' && '【手動実行】' || '' }}ワークフローが実行されました
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - run: |
          echo ${{ github.event.pull_request.head.sha }}
          echo ${{ github.event.workdlow_dispatch.head.sha }}
          echo ${{ github.workflow }}
          echo ${{ github.ref }}
          echo ${{ github.sha }}
